# Site wide configuration

title: Byron Wall
description: blog and portfolio of byron wall
logo: # 120x120 px default image used for Twitter summary card
teaser: A_Giraffe.jpg # 400x250 px default teaser image used in image archive grid
locale:
url: http://byroni.us

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Byron Wall
  email: byron@byroni.us
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:

#prose config
prose:
  rooturl: '_posts'
  siteurl: 'http://byroni.us'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""          


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
